jenkins-operator:
  jenkins:
    name: jenkins
    namespace: jenkins
    image: jenkins/jenkins:lts-alpine
    basePlugins:
      - name: kubernetes
        version: "1.30.11"
      - name: workflow-job
        version: "2.42"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: "4.9.0"
      - name: job-dsl
        version: "1.77"
      - name: configuration-as-code
        version: "1.54"
      - name: kubernetes-credentials-provider
        version: "0.20"
    
    plugins:
      - name: prometheus
        version: "2.0.10"

    backup:
      enabled: true
      image: virtuslab/jenkins-operator-backup-pvc:v0.1.1
      containerName: backup
      interval: 30

    configuration:
      configurationAsCode: {}
      #    - configMapName: jenkins-casc
      #      content: {}

    seedJobs:
      - id: jenkins-operator
        targets: "jobs/*.jenkins"
        description: "Jenkins Operator repository"
        repositoryBranch: main
        repositoryUrl: https://github.com/nicosto/jenkins-seed.git