kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-operator
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-operator
  namespace: jenkins-operator
roleRef:
  kind: Role
  name: jenkins-operator
  apiGroup: rbac.authorization.k8s.io